{{- with .Values.nrf }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "free5gc-nrf.fullname" $ }}-{{ .name }}
  labels:
    {{- include "free5gc-nrf.labels" $ | nindent 4 }}
    project: {{ $.Values.global.projectName }}
    nf: {{ .name }}
spec:
  selector:
    matchLabels:
      {{- include "free5gc-nrf.selectorLabels" $ | nindent 6 }}
      project: {{ $.Values.global.projectName }}
      nf: {{ .name }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/nrf-configmap.yaml") $ | sha256sum }}
      labels:
        {{- include "free5gc-nrf.selectorLabels" $ | nindent 8 }}
        project: {{ $.Values.global.projectName }}
        nf: {{ .name }}
    spec:
      containers:
      - name: {{ .name }}
        image: {{ .image.name }}:{{ .image.tag | default $.Chart.AppVersion }}
        imagePullPolicy: {{ .image.pullPolicy }}
        securityContext:
            {{- toYaml .securityContext | nindent 12 }}
        ports:
        - containerPort: {{ $.Values.global.nrf.service.port }}
        command: ["./nrf"]
        args: ["-c", "../config/nrfcfg.yaml"]
        env: 
          - name: DB_URI
            value: mongodb://{{ $.Values.mongodb.service.name }}/free5gc
          - name: GIN_MODE
            value: release
        volumeMounts:
        - mountPath: {{ .volume.mount }}
          name: {{ .volume.name }}
        resources:
            {{- toYaml .resources | nindent 12 }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      nodeSelector:
        {{- toYaml .nodeSelector | nindent 8 }}
      affinity:
        {{- toYaml .affinity | nindent 8 }}
      tolerations:
        {{- toYaml .tolerations | nindent 8 }}

      volumes:
      - name: {{ .volume.name }}
        projected:
          sources:
          - configMap:
              name: {{ .configmap.name }}
{{- end }}