nameOverride: ""
fullnameOverride: ""

global:
  projectName: free5gc
  nrf:
    service:
      name: nrf-nnrf
      type: ClusterIP
      port: "8000"
      nodePort: "30800"
  sbi:
    scheme: http

initcontainers:
  curl:
    registry: towards5gs
    image: initcurl
    tag: "1.0.0"
  busybox:
    image: busybox
    tag: "1.32.0"

db:
  enabled: true
# This section can be used to override the default values in the MongoDB chart (remember MongoDB is a subchart of the free5gcControlplane chart since control plane NFs rely on it. 
mongodb:
  fullnameOverride: "mongodb"
  useStatefulSet: true
  auth:
    enabled: false
  persistence:
    size: 6Gi
    mountPath: /bitnami/mongodb/data/db/
  service:
    name: mongodb
    type: ClusterIP
    port: 27017
    nodePort: "30017"

nrf:
  name: nrf
  replicaCount: 1
  image:
    name: towards5gs/free5gc-nrf
    pullPolicy: Always
  configmap:
    name: nrf-configmap
  volume:
    name: nrf-volume
    mount: /free5gc/config/
  configuration:
    serviceNameList: |-
      - nnrf-nfm
      - nnrf-disc
    configuration: |-
      DefaultPlmnId:
        mcc: 208
        mnc: 93
    logger:
      NRF:
        debugLevel: info
        ReportCaller: false
