{{- with .Values.smf }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "free5gc-smf.fullname" $ }}-{{ .name }}
  labels:
    {{- include "free5gc-smf.labels" $ | nindent 4 }}
    project: {{ $.Values.global.projectName }}
    nf: {{ .name }}
spec:
  {{- if not .autoscaling.enabled }}
  replicas: {{ .replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "free5gc-smf.selectorLabels" $ | nindent 6 }}
      project: {{ $.Values.global.projectName }}
      nf: {{ .name }}
  template:
    metadata:
      annotations:
        {{- include "free5gc-smf.smfAnnotations" $ | nindent 8 }}
        {{- if $.Values.isPfcpNeeded }}
        k8s.v1.cni.cncf.io/networks: '[
            { "name": "{{ $.Values.global.n4network.name }}-{{ .name }}",
              "interface": "n4",
              "ips": [ "{{ $.Values.global.smf.n4if.ipAddress }}/{{ $.Values.global.n4network.cidr }}" ],
              "gateway": [ "{{ $.Values.global.n4network.gatewayIP }}" ]
            }]'
        {{- end }}
        checksum/config: {{ include (print $.Template.BasePath "/smf-configmap.yaml") $ | sha256sum }}
      labels:
        {{- include "free5gc-smf.selectorLabels" $ | nindent 8 }}
        project: {{ $.Values.global.projectName }}
        nf: {{ .name }}
    spec:
      containers:
      - name: {{ .name }}
        image: {{ .image.name }}:{{ .image.tag | default $.Chart.AppVersion }}
        imagePullPolicy: {{ .image.pullPolicy }}
        securityContext:
            {{- toYaml .securityContext | nindent 12 }}
        ports:
        - containerPort: {{ .service.port }}
        ports:
        - name: nsmf
          containerPort: {{ .service.port }}
        {{- if $.Values.isPfcpNeeded }}
        - name: n4
          containerPort: 8805
          protocol: UDP
        {{- end }}
        command: ["./smf"]
        args: ["-c", "../config/smfcfg.yaml", "-u", "../config/uerouting.yaml"]
        env:
          - name: GIN_MODE
            value: release
        volumeMounts:
        - mountPath: {{ .volume.mount }}
          name: {{ .volume.name }}
        resources:
            {{- toYaml .resources | nindent 12 }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      nodeSelector:
        {{- toYaml .nodeSelector | nindent 8 }}
      affinity:
        {{- toYaml .affinity | nindent 8 }}
      tolerations:
        {{- toYaml .tolerations | nindent 8 }}

      volumes:
      - name: {{ .volume.name }}
        projected:
          sources:
          - configMap:
              name: {{ .configmap.name }}
              items:
              - key: smfcfg.yaml
                path: smfcfg.yaml
              - key: uerouting.yaml
                path: uerouting.yaml
{{- end }}